### ISSUE TITLE
app.astep does not work with declared context as input

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#439]
**Is your feature request related to a problem? Please describe.**
See title

**Describe the solution you'd like**
This should work

```python
    APP_ID = str(uuid.uuid4())
    PARTITION_KEY = str(uuid.uuid4())

    @action(reads=[], writes=[])
    def test_action(state: State, __context: ApplicationContext) -> State:
        assert __context.sequence_id == 0
        assert __context.partition_key == PARTITION_KEY
        assert __context.app_id == APP_ID
        return state

    app = (
        ApplicationBuilder()
        .with_actions(test_action)
        .with_entrypoint("test_action")
        .with_transitions()
        .with_identifiers(
            app_id=APP_ID,
            partition_key=PARTITION_KEY,
        )
        .build()
    )
    await app.astep()
```

```
Oh no an error! Need help with Burr?
Join our discord and ask for help! https://discord.gg/4FxBMyzW5n
-------------------------------------------------------------------
> Action: `test_action` encountered an error!<
> State (at time of action):
{'__SEQUENCE_ID': 0}
> Inputs (at time of action):
{}
********************************************************************************
Traceback (most recent call last):
  File "/Users/elijahbenizzy/dev/dagworks/os/burr/burr/core/application.py", line 971, in _astep
    return self._step(
           ^^^^^^^^^^^
  File "/Users/elijahbenizzy/dev/dagworks/os/burr/burr/core/application.py", line 811, in _step
    action_inputs = self._process_inputs(inputs, next_action)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elijahbenizzy/dev/dagworks/os/burr/burr/core/application.py", line 876, in _process_inputs
    raise ValueError(
ValueError: -------------------------------------------------------------------
Oh no an error! Need help with Burr?
Join our discord and ask for help! https://discord.gg/4FxBMyzW5n
-------------------------------------------------------------------
Inputs starting with a double underscore ({'__context'}) are reserved for internal use/injected inputs.Please do not directly pass keys starting with a double underscore.
```

**Comment by elijahbenizzy** [comment]
This has been fixed + released in 0.33.3
