### ISSUE TITLE
Bug Report - Docs - Cowsay Cookbook has an error in the code

### ISSUE THREAD

**Issue by nehiljain** [DAGWorks-Inc/burr#473]
[Cowsay cookbook](https://burr.dagworks.io/examples/simple/cowsay/) is not running as expected.

# Current behavior
1. When running the cookbook, `say_what` can be None.
2. `random.choice` errors out on a None object

## Stack Traces

```
Traceback (most recent call last):
  File "/Users/spalanimalai/.pyenv/versions/pretzelai/lib/python3.12/site-packages/burr/core/application.py", line 885, in _step
    result, new_state = _run_single_step_action(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/.pyenv/versions/pretzelai/lib/python3.12/site-packages/burr/core/application.py", line 287, in _run_single_step_action
    action.run_and_update(state, **inputs), action.name, action.schema
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/.pyenv/versions/pretzelai/lib/python3.12/site-packages/burr/core/action.py", line 655, in run_and_update
    return self._fn(state, **self._bound_params, **run_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/projects/demodrive-tests/burr/run_cowsay.py", line 30, in cow_said
    said = random.choice(say_what)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/.pyenv/versions/3.12.2/lib/python3.12/random.py", line 346, in choice
    if not len(seq):
           ^^^^^^^^
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/spalanimalai/projects/demodrive-tests/burr/run_cowsay.py", line 73, in <module>
    a_obj, result, state = app.step()
                           ^^^^^^^^^^
  File "/Users/spalanimalai/.pyenv/versions/pretzelai/lib/python3.12/site-packages/burr/core/application.py", line 672, in wrapper_sync
    return fn(app_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/.pyenv/versions/pretzelai/lib/python3.12/site-packages/burr/core/application.py", line 843, in step
    out = self._step(inputs=inputs, _run_hooks=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/.pyenv/versions/pretzelai/lib/python3.12/site-packages/burr/core/application.py", line 899, in _step
    raise e
  File "/Users/spalanimalai/.pyenv/versions/pretzelai/lib/python3.12/site-packages/burr/core/application.py", line 885, in _step
    result, new_state = _run_single_step_action(
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/.pyenv/versions/pretzelai/lib/python3.12/site-packages/burr/core/application.py", line 287, in _run_single_step_action
    action.run_and_update(state, **inputs), action.name, action.schema
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/.pyenv/versions/pretzelai/lib/python3.12/site-packages/burr/core/action.py", line 655, in run_and_update
    return self._fn(state, **self._bound_params, **run_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/projects/demodrive-tests/burr/run_cowsay.py", line 30, in cow_said
    said = random.choice(say_what)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/spalanimalai/.pyenv/versions/3.12.2/lib/python3.12/random.py", line 346, in choice
    if not len(seq):
           ^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

## Potential fix can be:
`if say_what is not None: said = random.choice(say_what); result["cow_said"] = cowsay.get_output_string("cow", said)`

# Additional context
This bug was found using an automation built by https://www.demodrive.tech/. We are looking at popular OSS projects and helping them ensure their documentation is error-proof.

**Comment by skrawcz** [comment]
Fixed in #475 thanks!
